name: check-release-version

on:
  release:
    types: [published]

jobs:
  check-version-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install package
        run: |
          IRIS_ENV=SERVER python -m pip install .

      - name: Check release tag
        run: |
          PYTHONPATH=. python scripts/ops/check_version_tag.py --release $RELEASE_VERSION
