[tool.coverage.report]
omit = ["tests/*", "*__init__.py", "*_version.py"]
exclude_lines = ["if __name__ == .__main__.:"]

[tool.ruff]
exclude = ["__init__.py"]
lint.select = ["E", "F", "PLC", "PLE", "PLR", "PLW"]
lint.ignore = ["E501", "F722", "F821", "PLR2004", "PLR0915", "PLR0913", "PLC0414", "PLR0402", "PLR5501", "PLR0911", "PLR0912", "PLW0603", "PLW2901"]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
src_paths = ["src", "tests"]

[tool.pydocstyle]
inherit = false
ignore = ["D100", "D104", "D203", "D205", "D211", "D213", "D406", "D407", "D413"]
match = ".*.py"

[tool.pytest]
minversion = 6.0
xfail_strict = true
log_auto_indent = true

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 120

include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
